apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
stringData: {{- tpl (.Values.config.secretEnv | toYaml) . | nindent 2 }}
